config/routes.rb
Autobots::Application.routes.draw do

  resources :ms_rnc_sgsns

  resources :ms_locations

  resources :raw_speedtests, :only => [:index, :show]

  resources :raw_pings, :only => [:index, :show]

  resources :raw_youtubes, :only => [:index, :show]

  resources :raw_https, :only => [:index, :show]

  resources :filters

  resources :links

  resources :nodes

  resources :time_configs

  resources :sgsns

  resources :rncs

  resources :visualizations

  resources :services do
    resources :metrics
  end

  resources :metrics do
    resources :filters
    resources :vspecs
    resources :selectfs
  end

  resources :metric_youtubes

  resources :metric_speedtests

  resources :metric_https

  resources :metric_pings

  devise_for :users
  resources :users

  namespace :api, defaults: {:format=> 'json'} do
    namespace :v1 do
      resources :facebooks do
        collection do
          get 'metric'
          get 'heatmap'
          get 'force'
          get 'metric_by_region'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :twitters do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :instagrams do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :pings do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :speedtests do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :youtubes do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :adhocs do
        collection do
          get 'heatmap'
        end

        member do
        end
      end

      resources :time_configs do
        collection do
        end

        member do
        end
      end

    end
  end

  root to: "static_pages#index"

  get 'heatmap' => 'static_pages#heatmap'
  get 'dashboards' => 'static_pages#dashboards'
  get 'access_denied' => 'static_pages#access_denied'

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user
  has_many :metrics, dependent: :destroy
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.order(:name)
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = current_user.services.new
    authorize! :manage, @service
  end

  # GET /services/1/edit
  def edit
    authorize! :manage, @service
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    authorize! :manage, @service

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    authorize! :manage, @service

    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    authorize! :manage, @service

    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :setttings, :model_name)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service, html: {class: "form-horizontal"} )  do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :name, class: "col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group field">
    <%= f.label :setttings, class: "col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :setttings, class: "form-control" %>
    </div>
  </div>
  <div class="form-group field">
    <%= f.label :model_name, class: "col-sm-2" %>
    <div class="col-sm-10">
      <%= f.select :model_name, options_for_select([['RawHttp', 'RawHttp'], ['RawPing', 'RawPing'], ['RawSpeedtest', 'RawSpeedtest'], ['RawYoutube', 'RawYoutube']], @service.model_name), {}, class: "form-control" %>
    </div>
  </div>
   <div class="form-group actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1 class="robot-page-header">Services</h1>


<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
<% if can? :manage, @service %>
      <th>Setttings</th>
      <th>Actions</th>
<% end %>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to service.name, service %></td>
        <td><%= service.model_name %></td>
<% if can? :manage, @service %>  
        <td><%= service.setttings %></td>
        <td>
          <%= link_to(edit_service_path(service), class: "robot-action-icon") do %>
            <i class="fa fa-pencil-square-o"></i>
          <% end -%> 
          <%= link_to(service_path(service), method: :delete, data: { confirm: 'Are you sure?' }, class: "robot-action-icon") do %>
            <i class="fa fa-trash-o"></i>
          <% end -%> 
        </td>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :manage, @service %>
  <%= link_to 'New Service', new_service_path %>
<% end %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @service.name %></h2>

<div class="panel panel-default">
  <div class="panel-heading">Metrics</div>
  <div class="panel-body">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Service</th>
          <th>Visualization</th>
<% if can? :manage, @service %>
          <th>Actions</th>
<% end %>
        </tr>
      </thead>

      <tbody>
        <% @service.metrics.each do |metric| %>
          <tr>
            <td><%= link_to metric.name, [metric.service, metric] %></td>
            <td><%= metric.service.name %></td>
            <td><%= metric.visualization.name %></td>
<% if can? :manage, @service %>              
            <td>
              <%= link_to(edit_service_metric_path(@service, metric), class: 'robot-action-icon') do %>
                <i class="fa fa-pencil-square-o"></i>
              <% end-%>
              <%= link_to([metric.service, metric], method: :delete, data: { confirm: 'Are you sure?' }, class: 'robot-action-icon') do %>
                <i class="fa fa-trash-o"></i>
              <% end-%>
            </td>
<% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
<% if can? :manage, @service %>     
    <%= link_to 'New Metric', new_service_metric_path(@service) %>
<% end %>    
  </div>
</div>

<% if can? :manage, @service %>  
  <br/>
  <%= link_to 'Edit', edit_service_path(@service) %> |
  <%= link_to 'Back', services_path %>
<% end %> 