config/routes.rb
Autobots::Application.routes.draw do

  resources :ms_rnc_sgsns

  resources :ms_locations

  resources :raw_speedtests, :only => [:index, :show]

  resources :raw_pings, :only => [:index, :show]

  resources :raw_youtubes, :only => [:index, :show]

  resources :raw_https, :only => [:index, :show]

  resources :filters

  resources :links

  resources :nodes

  resources :time_configs

  resources :sgsns

  resources :rncs

  resources :visualizations

  resources :services do
    resources :metrics
  end

  resources :metrics do
    resources :filters
    resources :vspecs
    resources :selectfs
  end

  resources :metric_youtubes

  resources :metric_speedtests

  resources :metric_https

  resources :metric_pings

  devise_for :users
  resources :users

  namespace :api, defaults: {:format=> 'json'} do
    namespace :v1 do
      resources :facebooks do
        collection do
          get 'metric'
          get 'heatmap'
          get 'force'
          get 'metric_by_region'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :twitters do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :instagrams do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :pings do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :speedtests do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :youtubes do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :adhocs do
        collection do
          get 'heatmap'
        end

        member do
        end
      end

      resources :time_configs do
        collection do
        end

        member do
        end
      end

    end
  end

  root to: "static_pages#index"

  get 'heatmap' => 'static_pages#heatmap'
  get 'dashboards' => 'static_pages#dashboards'
  get 'access_denied' => 'static_pages#access_denied'

end

app/models/visualization.rb
class Visualization < ActiveRecord::Base
  has_many :metrics
end

app/controllers/visualizations_controller.rb
class VisualizationsController < ApplicationController
  before_action :set_visualization, only: [:show, :edit, :update, :destroy]

  # GET /visualizations
  # GET /visualizations.json
  def index
    @visualizations = Visualization.all
  end

  # GET /visualizations/1
  # GET /visualizations/1.json
  def show
  end

  # GET /visualizations/new
  def new
    @visualization = Visualization.new
    authorize! :manage, @visualization
  end

  # GET /visualizations/1/edit
  def edit
    authorize! :manage, @visualization
  end

  # POST /visualizations
  # POST /visualizations.json
  def create
    @visualization = Visualization.new(visualization_params)
    authorize! :manage, @visualization

    respond_to do |format|
      if @visualization.save
        format.html { redirect_to @visualization, notice: 'Visualization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @visualization }
      else
        format.html { render action: 'new' }
        format.json { render json: @visualization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visualizations/1
  # PATCH/PUT /visualizations/1.json
  def update
    authorize! :manage, @visualization
    respond_to do |format|
      if @visualization.update(visualization_params)
        format.html { redirect_to @visualization, notice: 'Visualization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @visualization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visualizations/1
  # DELETE /visualizations/1.json
  def destroy
    @visualization.destroy
    respond_to do |format|
      format.html { redirect_to visualizations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visualization
      @visualization = Visualization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visualization_params
      params.require(:visualization).permit(:name, :view_path, :setting, :type, :config_file)
    end
end

app/helpers/visualizations_helper.rb
module VisualizationsHelper
end

app/views/visualizations/_form.html.erb
<%= form_for(@visualization) do |f| %>
  <% if @visualization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visualization.errors.count, "error") %> prohibited this visualization from being saved:</h2>

      <ul>
      <% @visualization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :view_path %><br>
    <%= f.text_field :view_path %>
  </div>
  <div class="field">
    <%= f.label :setting %><br>
    <%= f.text_field :setting %>
  </div>
  <div class="field">
    <%= f.label :type_viz %><br>
    <%= f.text_field :type_viz %>
  </div>
  <div class="field">
    <%= f.label :config_file %><br>
    <%= f.text_field :config_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visualizations/edit.html.erb
<h1>Editing visualization</h1>

<%= render 'form' %>

<%= link_to 'Show', @visualization %> |
<%= link_to 'Back', visualizations_path %>

app/views/visualizations/index.html.erb
<h1>Listing visualizations</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>View path</th>
      <th>Setting</th>
      <th>Type Viz</th>
      <th>Config file</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @visualizations.each do |visualization| %>
      <tr>
        <td><%= visualization.name %></td>
        <td><%= visualization.view_path %></td>
        <td><%= visualization.setting %></td>
        <td><%= visualization.type_viz %></td>
        <td><%= visualization.config_file %></td>
        <td><%= link_to 'Show', visualization %></td>
        <td><%= link_to 'Edit', edit_visualization_path(visualization) %></td>
        <td><%= link_to 'Destroy', visualization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visualization', new_visualization_path %>

app/views/visualizations/new.html.erb
<h1>New visualization</h1>

<%= render 'form' %>

<%= link_to 'Back', visualizations_path %>

app/views/visualizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @visualization.name %>
</p>

<p>
  <strong>View path:</strong>
  <%= @visualization.view_path %>
</p>

<p>
  <strong>Setting:</strong>
  <%= @visualization.setting %>
</p>

<p>
  <strong>Type:</strong>
  <%= @visualization.type_viz %>
</p>

<p>
  <strong>Config file:</strong>
  <%= @visualization.config_file %>
</p>


<%= link_to 'Edit', edit_visualization_path(@visualization) %> |
<%= link_to 'Back', visualizations_path %>