config/routes.rb
Autobots::Application.routes.draw do

  resources :ms_rnc_sgsns

  resources :ms_locations

  resources :raw_speedtests, :only => [:index, :show]

  resources :raw_pings, :only => [:index, :show]

  resources :raw_youtubes, :only => [:index, :show]

  resources :raw_https, :only => [:index, :show]

  resources :filters

  resources :links

  resources :nodes

  resources :time_configs

  resources :sgsns

  resources :rncs

  resources :visualizations

  resources :services do
    resources :metrics
  end

  resources :metrics do
    resources :filters
    resources :vspecs
    resources :selectfs
  end

  resources :metric_youtubes

  resources :metric_speedtests

  resources :metric_https

  resources :metric_pings

  devise_for :users
  resources :users

  namespace :api, defaults: {:format=> 'json'} do
    namespace :v1 do
      resources :facebooks do
        collection do
          get 'metric'
          get 'heatmap'
          get 'force'
          get 'metric_by_region'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :twitters do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :instagrams do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :pings do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :speedtests do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :youtubes do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :adhocs do
        collection do
          get 'heatmap'
        end

        member do
        end
      end

      resources :time_configs do
        collection do
        end

        member do
        end
      end

    end
  end

  root to: "static_pages#index"

  get 'heatmap' => 'static_pages#heatmap'
  get 'dashboards' => 'static_pages#dashboards'
  get 'access_denied' => 'static_pages#access_denied'

end

app/models/selectf.rb
class Selectf < ActiveRecord::Base
  belongs_to :metric
end

app/controllers/selectfs_controller.rb
class SelectfsController < ApplicationController
  before_action :set_metric
  before_action :set_selectf, only: [:show, :edit, :update, :destroy]

  # GET /selectfs
  # GET /selectfs.json
  def index
    @selectfs = @metric.selectfs.all
  end

  # GET /selectfs/1
  # GET /selectfs/1.json
  def show
  end

  # GET /selectfs/new
  def new
    @selectf = @metric.selectfs.new
    authorize! :manage, @selectf
  end

  # GET /selectfs/1/edit
  def edit
    authorize! :manage, @selectf
  end

  # POST /selectfs
  # POST /selectfs.json
  def create
    @selectf = @metric.selectfs.new(selectf_params)

    authorize! :manage, @selectf

    respond_to do |format|
      if @selectf.save
        format.html { redirect_to [@selectf.metric, @selectf], notice: 'Selectf was successfully created.' }
        format.json { render action: 'show', status: :created, location: @selectf }
      else
        format.html { render action: 'new' }
        format.json { render json: @selectf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selectfs/1
  # PATCH/PUT /selectfs/1.json
  def update
    authorize! :manage, @selectf

    respond_to do |format|
      if @selectf.update(selectf_params)
        format.html { redirect_to [@selectf.metric, @selectf ], notice: 'Selectf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @selectf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selectfs/1
  # DELETE /selectfs/1.json
  def destroy
    authorize! :manage, @selectf

    @selectf.destroy
    respond_to do |format|
      format.html { redirect_to [@metric.service, @metric] }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selectf
      @selectf = Selectf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selectf_params
      params.require(:selectf).permit(:field, :selected, :metric_id)
    end

    # Get metric
    def set_metric
      @metric = Metric.find(params[:metric_id])
    end
end

app/helpers/selectfs_helper.rb
module SelectfsHelper
end

app/views/selectfs/_form.html.erb
<%= form_for([@selectf.metric, @selectf], html: {class: "form-horizontal"}) do |f| %>
  <% if @selectf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selectf.errors.count, "error") %> prohibited this selectf from being saved:</h2>

      <ul>
      <% @selectf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group field">
    <%= f.label :field, class: "col-lg-2" %>
    <div class="col-lg-10">
      
      <%= f.select :field, options_for_select(@selectf.metric.service.model_name.constantize.attribute_names.map {|d| [d, d]}, selected: @selectf.field), {} , class: "form-control" %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :selected, class: "col-lg-2" %>
    <div class="col-lg-10">
      <%= f.check_box :selected, class: "" %>  
    </div>
  </div>

  <div class="form-group actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/selectfs/edit.html.erb
<h1>Editing selectf</h1>

<%= render 'form' %>

<%= link_to 'Show', [@selectf.metric, @selectf] %> |
<%= link_to 'Back', metric_selectfs_path(@selectf.metric) %>

app/views/selectfs/index.html.erb
<h1>Listing selectfs</h1>

<table>
  <thead>
    <tr>
      <th>Field</th>
      <th>Selected</th>
      <th>Metric</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @selectfs.each do |selectf| %>
      <tr>
        <td><%= selectf.field %></td>
        <td><%= selectf.selected %></td>
        <td><%= selectf.metric_id %></td>
        <td><%= link_to 'Show', selectf %></td>
        <td><%= link_to 'Edit', edit_selectf_path(selectf) %></td>
        <td><%= link_to 'Destroy', [selectf.metric, selectf], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selectf', new_selectf_path %>

app/views/selectfs/new.html.erb
<h1>New selectf</h1>

<%= render 'form' %>

<%= link_to 'Cancel', service_metric_path(@selectf.metric.service, @selectf.metric) %>

app/views/selectfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Field:</strong>
  <%= @selectf.field %>
</p>

<p>
  <strong>Selected:</strong>
  <%= @selectf.selected %>
</p>

<!-- <p>
  <strong>Metric:</strong>
  <%= @selectf.metric_id %>
</p>
 -->
<%= link_to 'Edit', edit_metric_selectf_path(@selectf.metric, @selectf) %> |
<%= link_to 'Back', service_metric_path(@selectf.metric.service, @selectf.metric) %>