config/routes.rb
Autobots::Application.routes.draw do

  resources :ms_rnc_sgsns

  resources :ms_locations

  resources :raw_speedtests, :only => [:index, :show]

  resources :raw_pings, :only => [:index, :show]

  resources :raw_youtubes, :only => [:index, :show]

  resources :raw_https, :only => [:index, :show]

  resources :filters

  resources :links

  resources :nodes

  resources :time_configs

  resources :sgsns

  resources :rncs

  resources :visualizations

  resources :services do
    resources :metrics
  end

  resources :metrics do
    resources :filters
    resources :vspecs
    resources :selectfs
  end

  resources :metric_youtubes

  resources :metric_speedtests

  resources :metric_https

  resources :metric_pings

  devise_for :users
  resources :users

  namespace :api, defaults: {:format=> 'json'} do
    namespace :v1 do
      resources :facebooks do
        collection do
          get 'metric'
          get 'heatmap'
          get 'force'
          get 'metric_by_region'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :twitters do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :instagrams do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :pings do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :speedtests do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :youtubes do
        collection do
          get 'metric'
        end

        member do
          get 'mapreduce'
          get 'mapreduce_join_mslocation'
        end
      end

      resources :adhocs do
        collection do
          get 'heatmap'
        end

        member do
        end
      end

      resources :time_configs do
        collection do
        end

        member do
        end
      end

    end
  end

  root to: "static_pages#index"

  get 'heatmap' => 'static_pages#heatmap'
  get 'dashboards' => 'static_pages#dashboards'
  get 'access_denied' => 'static_pages#access_denied'

end

app/models/filter.rb
class Filter < ActiveRecord::Base
  belongs_to :metric
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :set_metric
  before_action :set_filter, only: [:show, :edit, :update, :destroy]

  # GET /filters
  # GET /filters.json
  def index
    @filters = @metric.filters.all
  end

  # GET /filters/1
  # GET /filters/1.json
  def show
  end

  # GET /filters/new
  def new
    @filter = @metric.filters.new
    authorize! :manage, @filter
  end

  # GET /filters/1/edit
  def edit
    authorize! :manage, @filter
  end

  # POST /filters
  # POST /filters.json
  def create
    @filter = @metric.filters.new(filter_params)
    authorize! :manage, @filter

    respond_to do |format|
      if @filter.save
        format.html { redirect_to [@filter.metric, @filter], notice: 'Filter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @filter }
      else
        format.html { render action: 'new' }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filters/1
  # PATCH/PUT /filters/1.json
  def update
    authorize! :manage, @filter
    
    respond_to do |format|
      if @filter.update(filter_params)
        format.html { redirect_to [@filter.metric, @filter], notice: 'Filter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1
  # DELETE /filters/1.json
  def destroy
    authorize! :manage, @filter

    @filter.destroy
    respond_to do |format|
      format.html { redirect_to [@metric.service, @metric] }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter
      @filter = Filter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filter_params
      params.require(:filter).permit(:field, :description, :operation, :operand, :operand_type)
    end

    # Get metric
    def set_metric
      @metric = Metric.find(params[:metric_id])
    end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_form.html.erb
<%= form_for([@filter.metric, @filter], html: {class: "form-horizontal"}) do |f| %>
  <% if @filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
      <% @filter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :field, class: "col-lg-2" %>
    <div class="col-lg-10">
      
      <%= f.select :field, options_for_select(@filter.metric.service.model_name.constantize.attribute_names.map {|d| [d, d]}, selected: @filter.field), {} , class: "form-control" %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :operation, class: "col-lg-2" %>
    <div class="col-lg-10">
      
      <%= f.select :operation, options_for_select([['>', '>'], ['<', '<'], ['=', '='], ['!=', '!=']], selected: @filter.operation), {} , class: "form-control" %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :operand, class: "col-lg-2" %>
    <div class="col-lg-10">
      <%= f.text_field :operand %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :operand_type, class: "col-lg-2" %>
    <div class="col-lg-10">
      
      <%= f.select :operand_type, options_for_select([['integer', 'integer'], ['float', 'float'], ['string', 'string'],['nil', 'nil']], selected: @filter.operand_type), {} , class: "form-control" %>
    </div>
  </div>

  <div class="form-group field">
    <%= f.label :description, class: "col-lg-2" %>
    <div class="col-lg-10">
      <%= f.text_area :description %>
    </div>
  </div>

<!--   <div class="field">
    <%= f.label :metric_id %><br>
    <%= f.number_field :metric_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filters/edit.html.erb
<h1>Editing filter</h1>

<%= render 'form' %>

<%= link_to 'Cancel', service_metric_path(@filter.metric.service, @filter.metric) %>

app/views/filters/index.html.erb
<h1>Listing filters</h1>

<table>
  <thead>
    <tr>
      <th>Field</th>
      <th>Operation</th>
      <th>Operand</th>
      <th>Operand Type</th>
      <th>Description</th>
      <th>Metric</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @filters.each do |filter| %>
      <tr>
        <td><%= filter.field %></td>
        <td><%= filter.operation %></td>
        <td><%= filter.operand %></td>
        <td><%= filter.operand_type %></td>
        <td><%= filter.description %></td>
        <td><%= filter.metric_id %></td>
        <td><%= link_to 'Show', filter %></td>
        <td><%= link_to 'Edit', edit_filter_path(filter) %></td>
        <td><%= link_to 'Destroy', filter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Filter', new_filter_path %>

app/views/filters/new.html.erb
<h1>New filter</h1>

<%= render 'form' %>

<%= link_to 'Back', service_metric_path(@filter.metric.service, @filter.metric) %>

app/views/filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Field:</strong>
  <%= @filter.field %>
</p>

<p>
  <strong>Opearation:</strong>
  <%= @filter.operation %>
</p>

<p>
  <strong>Opearand:</strong>
  <%= @filter.operand %>
</p>

<p>
  <strong>Opearand Type:</strong>
  <%= @filter.operand_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @filter.description %>
</p>

<p>
  <strong>Metric:</strong>
  <%= @filter.metric_id %>
</p>

<%= link_to 'Edit', edit_metric_filter_path(@filter.metric, @filter) %> |
<%= link_to 'Back', service_metric_path(@filter.metric.service, @filter.metric) %>